<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
		<td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="http://aps.ncue.edu.tw/exampg_m/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="http://aps.ncue.edu.tw/exampg_m/images/space.gif" width="1" height="2"></td>
				</tr>
				<tr> 
					<td background="http://aps.ncue.edu.tw/exampg_m/images/shadow.jpg"><img src="http://aps.ncue.edu.tw/exampg_m/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5" bgcolor="#FFFFFF">
							<tr> 
								<td>親愛的考生您好：</td>
							</tr>
							<tr> 
								<td>　　感謝您使用本校網路招生系統，您所繳交之費用業已入帳。</td>
							</tr>
							<tr> 
								<td>　　網路訂購之紙本簡章，於<font color=red>每星期二、星期五</font>寄發。姓名或地址如有罕用字，請另填寫<a href='http://aps.ncue.edu.tw/exampg_m/code_reply.doc' target=_blank>罕用字回覆表</a>傳真本校處理。若最近之寄發日期後三日仍未收到簡章，請儘速與本校招生組聯絡。</td>
							</tr>
							<tr>
								<td>　　簡章內頁附有一組序號、密碼及繳費帳號，此為網路報名使用；您必須先利用報名費繳費帳號(<font color=red>99216-81xxxxxx-x</font>)繳完報名費後，才可進行<a href=http://aps.ncue.edu.tw/exampg_m/signup_login.php traget=_blank>網路報名</a>作業。</td>
							</tr>							
							<tr> 
								<td>　　　　祝您　金榜題名</td>
							</tr>
							<tr> 
								<td align="right">國立彰化師範大學　網路報名系統</td>
							</tr>
						</table></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><div align="right"></div></td>
				</tr>
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="http://aps.ncue.edu.tw/exampg_m/" target="_blank">
</map>
</body>
</html>
