<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
		<td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="BASEURL/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="BASEURL/images/space.gif" width="1" height="2"></td>
				</tr>
				<tr> 
					<td background="BASEURL/images/shadow.jpg"><img src="BASEURL/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5">
							<tr> 
								<td>親愛的考生您好：</td>
							</tr>
							<tr> 
								<td>　　以下是您的序號及密碼( 繳費帳號：account_no，金額：pay_money 元 )，在使用報名系統上後續之各項服務時，將會需要您輸入序號及密碼(<font color=red>建議使用複製、貼上，以避免輸入錯誤</font>)，請您務必妥善保存。</td>
							</tr>
							<tr> 
								<td><p>　　<font color="#0000FF">序號：<u>snum</u><span style="font-size:12px;color:red"> (共10碼，第1碼為大寫英文字母，2-10碼為數字。)</span><br>
										　　密碼：<u>pswd</u><span style="font-size:12px;color:red"> (共10碼，由英文字母和數字組成，英文字母一律大寫。)</span></font></p>
									</td>
							</tr>
							<tr> 
								<td align="right">國立彰化師範大學　網路報名系統</td>
							</tr>
						</table></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><div align="right"></div></td>
				</tr>
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="BASEURL/" target="_blank">
</map>
</body>
</html>
