<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
.style1 {
	color: #FF0000;
	font-weight: bold;
}
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="http://aps.ncue.edu.tw/exampg_m/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="http://aps.ncue.edu.tw/exampg_m/images/space.gif" width="1" height="2"></td>
				</tr>				
				<tr>
				    <td background = "http://aps.ncue.edu.tw/exampg_m/images/shadow.jpg" >
				    <img src="http://aps.ncue.edu.tw/exampg_m/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5" bgcolor="#FFFFFF">
							<tr> 
								<td><p align="center"><strong>國立彰化師範大學act_year_no學年度碩士班招生考試<br>
								</strong><strong>備取生錄取通知單 </strong></p>
						      </td>
							</tr>
                            <tr> 
								<td>親愛的 stud_name 先生/小姐，您好：</td>
							</tr>
							<tr> 
								<td>　　
								  台端參加本校act_year_no學年度碩士班招生考試，成績業經招生委員會評定錄取為備取生（錄取系所：organize_id ，備取順位：第 backnumber 名），請依本通知單規定辦理<u>備取生報到</u>事宜。<br>
								  <table width="100%" border="0">
                                    <tr>
                                      <td valign="top">一、</td>
                                      <td colspan="3"><p>請備取生於<span class="style1">104年4月12日（日）上午10時30分前</span>抵達進德校區格致館5樓生物系辦辦理報到，上午10時30分開始唱名遞補，獲遞補時請繳交：(一)二吋半身脫帽光面近照相片乙張。(二)身分證或學生證正本（查驗用）及影本乙份。（三）學位證書正本或同等學力證書正本【如：高特考身分繳驗及格證書；專科畢業繳驗畢業證書；肄業身分繳驗修業證明書】。</p></td>
                                    </tr>                                                       
                                    <tr>
                                      <td valign="top">二、</td>
                                      <td colspan="3">無法親自報到者可委託他人辦理（須繳交委託書），但須將證件繳交齊全。應屆畢業生無法繳交學位證書正本者，請填寫切結書，並請於<u>104年7月15日（三）中午12時前</u>至錄取系所補繳學位證書正本。未在規定時間內完成報到者，以放棄入學資格論，由其他備取生依序遞補。【應屆畢業生因故未能於<u>104年7月15日（三）中午12時前</u>繳交畢業證書者，須請原就讀學校開立證明，並敘明原因。】</td>
                                    </tr>
                                    <tr>
                                      <td valign="top">三、</td>
                                      <td colspan="3"><p>逾開始唱名時間（4月12日上午10:30）未出席，即視同自願放棄遞補資格，由其他備取生依序遞補，額滿為止。</p>                                      </td>
                                    </tr>                                    
                                  </table>
								  <p align="right" style="font-size:14px">國立彰化師範大學招生委員會　　啟 </p>
					          <div align="center" style="font-size:14px"></div></td>
					  </tr>							
							<tr> 
								<td><font color=blue>　</font></td>
					  </tr>						
				  </table></td>
				</tr>
				
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="http://aps.ncue.edu.tw/exampg_m/" target="_blank">
</map>
</body>
</html>
