<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="BASEURL/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="BASEURL/images/space.gif" width="1" height="2"></td>
				</tr>				
				<tr>
				    <td background = "BASEURL/images/shadow.jpg" >
				    <img src="BASEURL/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5" bgcolor="#FFFFFF">
							<tr> 
								<td>親愛的考生您好：</td>
							</tr>
							<tr> 
								<td>　　感謝您使用本校網路招生系統，您所繳交之報名費( 繳費帳號：account_no，金額：pay_money 元 )業已入帳，以下是您個人專用的序號及密碼，使用本系統各項服務時，將會需要您輸入序號及密碼(<font color=red>建議使用複製、貼上，以避免輸入錯誤</font>)，請您務必妥善保存。<font color=#FF0000>本校人員不會主動要求您提供序號及密碼</font>。</td>
							</tr>							
							<tr> 
								<td><font color=blue>　序號：snum </font>(共10碼，<font color=red>第1碼為大寫英文字母，2-10碼為數字</font>。)<br>
								<font color=blue>　密碼：pswd </font>(共10碼，<font color=red>由英文字母和數字組成，英文字母一律大寫</font>。)<br>
									<font color=red><br>　　您可以利用此組序號密碼登入系統進行<a href=BASEURL/signup.php traget=_blank>填寫報名表</a>作業。<br></font></font>
								</td>
							</tr>
							<tr> 
								<td>　　網路報名日期為【startdate】 至 【enddate】 止 。 </td>
							</tr>
							<tr>
								<td>若您遺失序號及密碼，請利用「資料查詢」功能裡的「查詢序號密碼」，系統將會重新傳送至您的電子郵件信箱，謝謝。</p></td>
							</tr>
							<tr> 
								<td>　　　　祝您　金榜題名</td>
							</tr>
							<tr> 
								<td align="right">國立彰化師範大學　網路報名系統</td>
							</tr>
						</table></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><div align="right"></div></td>
				</tr>
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="BASEURL/" target="_blank">
</map>
</body>
</html>
