<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
.style1 {
	color: #FF0000;
	font-weight: bold;
}
.style2 {color: #FF0000}
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="https://aps.ncue.edu.tw/exampg_m_new/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="https://aps.ncue.edu.tw/exampg_m_new/images/space.gif" width="1" height="2"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5" bgcolor="#FFFFFF">
							<tr> 
								<td><p align="center"><strong>國立彰化師範大學act_year_no學年度碩士班招生考試<br>
								</strong><strong>正(備)取生錄取通知單</strong></p>						      </td>
							</tr>
                            <tr> 
								<td>親愛的 stud_name 先生/小姐，您好：</td>
							</tr>
							<tr> 
								<td>　　
								  台端參加本校act_year_no學年度碩士班招生考試，成績業經招生委員會評定錄取為正(備)取生。 <br>
								  <table width="100%" border="0">
                                  <tr>
                                    <td  valign="top">一、</td>
                                      <td colspan="3">正取生現場報到及驗證：需於本校第一階段開放成績複查截止日後五個工作日內<span class="style2">（4月23日前）9:00 ~ 16:00</span>至錄取系所辦公室辦理現場報到及驗證【正、備取生無須上網登錄就讀（遞補）意願】。</td>
                                    </tr>                                    
                                    <tr>
                                      <td  valign="top" width="30">二、</td>
                                      <td colspan="3">正、備取生遞補作業：同時獲正取及備取不同系所，只能擇一系所報到。各系所碩士班（組）正取生報到後之缺額，由各系所辦公室通知備取生依備取順序遞補之。備取通知遞補時，若已報到其他工學院各系所碩士班（組），須於接獲通知三個工作日內至原報到系所辦理放棄，方得至遞補系所報到。</td>
                                    </tr>                                    
                                    <tr>
                                      <td valign="top">三、</td>
                                      <td colspan="3">餘相關資訊請詳見紙本通知。</td>
                                    </tr>                                                                     
                                  </table>
								  <p align="right" style="font-size:14px">國立彰化師範大學招生委員會　　啟 </p>
					          <div align="center" style="font-size:14px"></div></td>
					  </tr>
				  </table></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><div align="right"></div></td>
				</tr>
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="https://aps.ncue.edu.tw/exampg_m_new/" target="_blank">
</map>
</body>
</html>
