<html>
  <head>
    <style>
      .button {
        border-right: #993300 1px solid;
        padding-right: #fdd2b3 0px;
        border-top: #993300 1px solid;
        padding-left: #fdd2b3 0px;
        padding-bottom: #fdd2b3 0px;
        border-left: #993300 1px solid;
        line-height: 150%;
        padding-top: #fdd2b3 0px;
        border-bottom: #993300 1px solid;
        height: 150%;
        background-color: #ffffff;
        text-align: center;
        text-decoration: none;
        font-size: 12;
        color: #993300;
      }
      td {
        color: #464646;
        font: 10pt;
        line-height: 150%;
      }
      .style1 {
        color: #ff0000;
        font-weight: bold;
      }
      .style2 {
        color: #ff0000;
      }
    </style>
  </head>
  <body>
    <table
      width="500"
      border="1"
      align="center"
      cellpadding="0"
      cellspacing="0"
      bordercolor="#009900"
    >
      <tr>
        <td>
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr bgcolor="#FFFFFF">
              <td>
                <img
                  src="BASEURL/images/bn_mail.jpg"
                  width="500"
                  height="75"
                  border="0"
                  usemap="#Map"
                />
              </td>
            </tr>
            <tr bgcolor="#FFFFFF">
              <td bgcolor="#009900">
                <img
                  src="BASEURL/images/space.gif"
                  width="1"
                  height="2"
                />
              </td>
            </tr>
            <tr>
              <td
                background="BASEURL/images/shadow.jpg"
              ></td>
            </tr>
            <tr bgcolor="#FFFFFF">
              <td>
                <table
                  width="100%"
                  border="0"
                  cellspacing="0"
                  cellpadding="5"
                  bgcolor="#FFFFFF"
                >
                  <tr>
                    <td>
                      <p align="center">
                        <strong
                          >國立彰化師範大學act_year_no學年度博士班招生考試<br /> </strong
                        ><strong>推薦函填寫通知</strong>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td>親愛的 r_name 師長，您好：</td>
                  </tr>
                  <tr>
                    <td>
                      　　 報考人 stud_name 報考國立彰化師範大學 dept_name
                      博士班招生考試，請您於<span
                        style="font-size: 17px; color: red"
                      >
                        su_end_date </span
                      >前至本校網路報名系統《
                      <a
                        href="BASEURL/letter_fill.php?token=r_token"
                        target="_blank"
                        >線上填寫推薦函</a
                      >
                      》，感謝您的協助！
                      <br /><br />

                      <p align="right" style="font-size: 14px">
                        國立彰化師範大學招生委員會　　啟
                      </p>
                      <br />
                      <p>
                        聯絡資訊：<br />
                        機關電話：04-7232105 (總機)　
                        　研究所招生試務：5632~5637(分機)　<br />
                      </p>
                      <div align="center" style="font-size: 14px"></div>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr bgcolor="#FFFFFF">
              <td><div align="right"></div></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    <map name="Map">
      <area
        shape="rect"
        coords="424,55,492,71"
        href="BASEURL/"
        target="_blank"
      />
    </map>
  </body>
</html>
