<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
		<td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="https://aps.ncue.edu.tw/exampg_m_new/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="https://aps.ncue.edu.tw/exampg_m_new/images/space.gif" width="1" height="2"></td>
				</tr>
				<tr> 
					<td background="https://aps.ncue.edu.tw/exampg_m_new/images/shadow.jpg"><img src="https://aps.ncue.edu.tw/exampg_m_new/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5">
							<tr> 
								<td>usrname　先生/小姐您好：</td>
							</tr>
							<tr> 
								<td>　　您已報名本校act_year_no學年度碩士班招生考試(<span style="font-weight:bold;color:red">筆試日期：exam_date</span>)，請您利用報名時序號密碼登入系統進行<a href='https://aps.ncue.edu.tw/exampg_m/cardprint_login.php' traget='_blank'>准考證列印</a>作業。</td>
							</tr>								
							<tr><td><span style="font-weight:bold;color:red">准考證由考生自行下載列印，請以A4白紙單面列印，本校不再另行寄發。</span></td></tr> 
							<tr><td>　　准考證下載日期為【card_start_date】 至 【card_end_date】 止 。</td></tr> 
				 
							<tr> 
								<td>　　　　祝您　金榜題名</td>
							</tr>
							<tr> 
								<td align="right">國立彰化師範大學　網路報名系統</td>
							</tr>
						</table></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><div align="right"></div></td>
				</tr>
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="https://aps.ncue.edu.tw/exampg_m_new/" target="_blank">
</map>
</body>
</html>
