<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
		<td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="https://aps.ncue.edu.tw/exampg_m_new/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="https://aps.ncue.edu.tw/exampg_m_new/images/space.gif" width="1" height="2"></td>
				</tr>
				<tr> 
					<td background="https://aps.ncue.edu.tw/exampg_m_new/images/shadow.jpg"><img src="https://aps.ncue.edu.tw/exampg_m_new/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5">
							<tr> 
								<td>usrname　先生/小姐您好：</td>
							</tr>
							<tr> 
								<td>　　您已完成全部報名程序，謝謝您使用本校網路報名系統，也請您密切注意本校各項考試資訊。</td>
							</tr>
							<tr> 
								<td>　　資料確認完成日期時間： con_date</td>
							</tr>
							<tr> 
								<td>　　身心障礙考生如欲申請各項應考需求，請另寄交申請表及證明文件至本校招生委員會。</td>
							</tr>
							<tr> 
								<td>　　報名資料如有罕用字，致電腦無法正常顯示者，請另填<a href='https://aps.ncue.edu.tw/exampg_m_new/code_reply.doc' target=_blank>罕用字回覆表</a>傳真本校處理。</td>
							</tr>
							<tr><td>　　准考證由考生自行下載列印，請於開放列印日期：card_start_date 起至 card_end_date 止，至<b>網路報名系統 / 網路報名 / 准考證列印</b> 下載(不限次數)後，以A4白紙單面紙張自行列印，並妥為保存，本校不再另行寄發。</td></tr> 
				
							<tr><td>　　以同等學力報考者，須於報名截止前將同等學力證件影本寄送達本校招生委員會審查。未繳驗證件者，如獲錄取，於報到時學力證件審查不合格，須撤銷錄取資格，不得異議。</td></tr>
							<!--<tr><td>　　報考特殊教育學系公費生及特殊教育學系資賦優異教育碩士班公費生者，須於報名截止日前將學歷證件及合格教師證影本寄送達至本校特殊教育學系審查，審查未通過者不受理報名，如未繳驗證件，則視同報考資格不符。</td></tr>-->
							<tr><td>　　招生系所如須郵寄備審資料，請依各招生系所簡章規定之截止期限前寄(送)達備審資料。</td></tr>
							<tr> 
								<td>　　報名資料如下：</td>
							</tr>
							<tr> 
								<td>　　finaldata</td>
							</tr>
							<tr> 
								<td>　　注意事項：</td>
							</tr>
							<tr> 
								<td>　　．資料庫已鎖定您的報名資料，不得再修改資料。</td>
							</tr>
							<tr> 
								<td>　　．網路報名部份之權限已關閉，您無法再使用網路報名功能，其它功能皆可正常使用。</td>
							</tr>
							<tr> 
								<td>　　</td>
							</tr>
							<tr> 
								<td>　　　　祝您　金榜題名</td>
							</tr>
							<tr> 
								<td align="right">國立彰化師範大學　網路報名系統</td>
							</tr>
						</table></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><div align="right"></div></td>
				</tr>
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="https://aps.ncue.edu.tw/exampg_m_new/" target="_blank">
</map>
</body>
</html>
