<html>
<head>
<style>
 .button { BORDER-RIGHT: #993300 1px solid; PADDING-RIGHT: #FDD2B3 0px; BORDER-TOP: #993300 1px solid; PADDING-LEFT: #FDD2B3 0px; PADDING-BOTTOM: #FDD2B3 0px; BORDER-LEFT: #993300 1px solid; LINE-HEIGHT: 150%; PADDING-TOP: #FDD2B3 0px; BORDER-BOTTOM: #993300 1px solid; HEIGHT: 150%; BACKGROUND-COLOR: #FFFFFF; TEXT-ALIGN: center ; TEXT-DECORATION: none ;font-size:12 ;color: #993300; }
td { color:#464646; font: 10pt; line-height: 150% }
.style1 {
	color: #FF0000;
	font-weight: bold;
}
</style>
</head>
<body>
<table width="500" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#009900">
	<tr>
	  <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr bgcolor="#FFFFFF"> 
					<td><img src="http://aps.ncue.edu.tw/exampg_m/images/bn_mail.jpg" width="500" height="75" border="0" usemap="#Map"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td bgcolor="#009900"><img src="http://aps.ncue.edu.tw/exampg_m/images/space.gif" width="1" height="2"></td>
				</tr>				
				<tr>
				    <td background = "http://aps.ncue.edu.tw/exampg_m/images/shadow.jpg" >
				    <img src="http://aps.ncue.edu.tw/exampg_m/images/space.gif" width="1" height="15"></td>
				</tr>
				<tr bgcolor="#FFFFFF"> 
					<td><table width="100%" border="0" cellspacing="0" cellpadding="5" bgcolor="#FFFFFF">
							<tr> 
								<td><p align="center"><strong>國立彰化師範大學act_year_no學年度碩士班招生考試<br>
								</strong><strong>備取生錄取通知單 </strong></p>
						      </td>
							</tr>
                            <tr> 
								<td>親愛的 stud_name 先生/小姐，您好：</td>
							</tr>
							<tr> 
								<td>　　
								  台端參加本校act_year_no學年度碩士班招生考試，成績業經招生委員會評定錄取為備取生，請依本通知單規定辦理申明遞補意願事宜。<br>
								  <table width="100%" border="0">
                                    <tr>
                                      <td width="30">一、</td>
                                      <td colspan="3">申明遞補意願期間：<span class="style1"><u>即日起至104年4月24日(星期五)下午5時止</u></span>。</td>
                                    </tr>
                                    
                                    <tr>
                                      <td>二、</td>
                                      <td colspan="3">申明遞補意願方式：</td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                      <td width="25" valign="top">(一)</td>
                                      <td width="421" colspan="2"><p>本階段以網路登錄方式辦理。請在截止日前至本校「網路報名系統」(<a href="http://aps.ncue.edu.tw/exampg_m/" target="_blank">http://aps.ncue.edu.tw/exampg_m/</a>)選擇「報到相關」項下之「正（備）取生申明就讀（遞補）意願」功能，輸入您的認證碼後登錄遞補意願，<span class="style1"><u>逾期視同放棄備取遞補資格</u></span>。 <br>
                                      <strong><u>※您的認證碼為：auth_code</u></strong> </p></td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                      <td valign="top">(二)</td>
                                      <td colspan="2">已獲錄取聯合招生系所之正取生，如已申明就讀（遞補）意願，無須再重新申明；備取多個招生系所者，僅須申明一次就讀（遞補）意願，如未申明，則視為放棄遞補資格。</td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                      <td valign="top">(三)</td>
                                      <td colspan="2">經擇優錄取方案之備取生，僅須至原報考系所申明遞補意願，其擇優方案遞補意願以原報考系所申明為準。如未至原報考系所申明，則視為放棄擇優錄取方案之遞補資格。</td>
                                    </tr>
                                    <tr>
                                      <td>&nbsp;</td>
                                      <td valign="top">(四)</td>
                                      <td colspan="2">如無法順利完成登錄，請在申明遞補意願截止日前(上班時間08:00～17:00)與本校教務處教學資源組聯絡，電話：(04)7232105轉分機5634。</td>
                                    </tr>                                    
                                    <tr>
                                      <td valign="top">三、</td>
                                      <td colspan="3"><strong><u>104年4月27日</u></strong>上午10時起，可上網查詢錄取系(所)研究生網路報到情形。網址：本校「網路報名系統」選擇「報到相關」項下之「正備取生報到狀況」；如有疑義，請向各系(所)辦公室洽詢。</td>
                                    </tr>
                                    <tr>
                                      <td valign="top">四、</td>
                                      <td colspan="3"><p>正取生如有放棄或未報到，其缺額由本校招生委員會主動以書面限時通知下一順位備取生遞補，備取生應依報到通知之規定辦理報到手續。 <br>
                                        (書面限時通知以報名時考生所填之<strong><u>通訊地址</u></strong>限時信函寄發，如因無人收件或住址填寫錯誤，致未能如期報到者，考生自負責任；通訊地址如有異動，請即向本校教務處教學資源組更正)。</p>                                      </td>
                                    </tr>
                                    <tr>
                                      <td valign="top">五、</td>
                                      <td colspan="3">依簡章規定本招生考試遞補最後期限為本校104學年度行事曆所定之開始上課日止。</td>
                                    </tr>
                                    <tr>
                                      <td valign="top">&nbsp;</td>
                                      <td colspan="3"><span style="color:blue;font-size:15px">遞補順序：union_priority</span></td>
                                    </tr>
                                    <tr>
                                      <td valign="top">&nbsp;</td>
                                      <td colspan="3">&nbsp;</td>
                                    </tr>  
                                  </table>
								  <p align="right" style="font-size:14px">國立彰化師範大學招生委員會　　啟 </p>
					          <div align="center" style="font-size:14px"></div></td>
					  </tr>							
							<tr> 
								<td><font color=blue>　</font></td>
					  </tr>						
				  </table></td>
				</tr>
				
			</table></td>
	</tr>
</table>
<map name="Map">
    <area shape="rect" coords="424,55,492,71" href="http://aps.ncue.edu.tw/exampg_m/" target="_blank">
</map>
</body>
</html>
